### PR TITLE
Reports UI

### PR DESCRIPTION
**Pull request by pkarman**
trello: https://trello.com/c/eDpZUSEb/79-as-a-user-i-can-subscribe-to-a-saved-report-so-that-i-can-automatically-receive-updates

### CODE REVIEW

**Comment by pkarman** [comment]
screen shot 2016-03-09 at 4 24 23 pm
screen shot 2016-03-09 at 4 25 06 pm

**Comment by jessieay** [comment]
@pkarman merge conflicts :cry:

**Comment by pkarman** [comment]
@jessieay thanks - resolved

**Comment by jessieay** [comment]
@pkarman are there plans to do some more design on this? functionality all looks good on c2-dev-jessieay but it did take me a bit to figure out how to find the page in the screenshot above (assumed "view details" would show results, not page for email prefs)

if we are going to revisit design, then I will merge as-is. Otherwise, can we create a card for usability of this?

**Comment by ericronne** [comment]
@jessieay this is definitely an "mvf"-level design, and my only change req @pkarman would be to make the report titles *not* links. Currently clicking on the titles runs a report, but it should no longer function in that manner. Instead they have to click the run button. thx!

**Comment by pkarman** [comment]
thanks @ericronne -- report names unlinked in 03ef659

**Comment by jessieay** [comment]
sounds good!

**Pull request merged**
