### PR TITLE
Add comment text to Proposal update emails

### PR DESCRIPTION
**Pull request by jessieay**
* Add specs for `Ncr::WorkOrderUpdater`, too

screen shot 2016-03-09 at 5 40 56 pm

https://trello.com/c/nbI2mxDU/150-10-email-conversion-approver-modified-request-for-an-awaiting-approval

### CODE REVIEW

**Comment by jessieay** [comment]
Note that this design is slightly different from the mocks. I spoke with Amber about this. Since our current update comments have this format, we decided to stick with it. If we want to change how update text looks in email, we should update the `comment.comment_text` data to look the same so we can be consistent.

**Comment by jessieay** [comment]
updates to comment only version: 

screen shot 2016-03-09 at 5 37 32 pm

**Comment by rememberlenny** [comment]
@jessieay Tested in browser runner. 

Looks good for first pass.

iphone6s-vertical-allowed-1366
chromegmailnew-vertical-allowed-1366
ol2013-vertical-allowed-1366

**Comment by jessieay** [comment]
This should be green now (needed a small update in specs 1a605aa0

@rememberlenny can you review ?

**Pull request merged**
