### PR TITLE
[Delivers #105569568] Use `example.com` for all test email addresses

### PR DESCRIPTION
**Pull request by jessieay**
* https://www.advomatic.com/blog/what-to-use-for-test-email-addresses

### CODE REVIEW

**Comment by pkarman** [comment]
maybe `example.gov` as an homage to our roots?

I like consistency, but also enjoy seeing the programmer personality in some of these. I'm +0 on this.

**Comment by jessieay** [comment]
@pkarman `example.gov` is not a reserved second level domain name:  https://tools.ietf.org/html/rfc2606

I also like personality but we really should be sticking with reserved domains in tests for the reasons cited in the blog post linked to in the PR description. We can still have fun with strings!

**Comment by jessieay** [comment]
@pkarman this is another good blog post on RFC2606 http://www.techrepublic.com/blog/it-security/use-rfc-2606-example-domains-for-example-emails/

**Comment by pkarman** [comment]
Those are reasonable arguments. +1 from me.

Note there there are multiple instances of `.gov` test emails in the `spec/` space as well. You might want to include those in this PR.

**Comment by jessieay** [comment]
@pkarman good call, forgot to grep for ".gov" 

All ".gov" addresses changed to "example.com" in 6ed74a24272dabf8aeb7571ae35414c5b48bd04a

**Comment by pkarman** [comment]
@jessieay looks like this needs a merge from master to resolve conflicts. After that, I am happy to merge.

**Comment by jessieay** [comment]
@pkarman rebased. Thanks for the heads up re: merge conflicts

**Comment by jessieay** [comment]
@pkarman build is now passing! :checkered_flag:

**Pull request merged**
