### PR TITLE
[Delivers #103441298] admin ui

### PR DESCRIPTION
**Pull request by pkarman**
Story: https://www.pivotaltracker.com/story/show/103441298

This PR uses the [activeadmin gem](https://github.com/activeadmin/activeadmin) to implement an `/admin` URL namespace for managing users and roles. Basic searching and CRUD are supported.

### CODE REVIEW

**Comment by pkarman** [comment]
depends upon #618 merge to master and then to this branch, for tests to start passing.

**Comment by pkarman** [comment]
@yozlet handing this to you for review

**Comment by yozlet** [comment]
Any particular reason for pulling the gem from Github rather than rubygems?

**Comment by yozlet** [comment]
QA'ed with @annalee. :+1: :shipit:

**Comment by annalee** [comment]
QA'd with @yozlet and we think it's ready to :ship:

**Comment by pkarman** [comment]
the rubygems 1.0.0.pre2 release shipped Sept 23 (after I started this branch) and the previous release was 6 mos old and lacked a bunch of rails 4 fixes. We could switch over to rubygems now, though I suspect that until 1.0.0 is final, we might benefit from tracking master instead.

**Comment by yozlet** [comment]
@pkarman: Yep, sounds good to me.

**Pull request merged**
