### PR TITLE
Add Railroady diagram of models

### PR DESCRIPTION
**Pull request by jessieay**
* https://github.com/preston/railroady
* Part of ATO
* Step of https://www.pivotaltracker.com/story/show/90140624
* Removed unused AR model since it was causing railroady to fail

### CODE REVIEW

**Comment by jessieay** [comment]
Approver comments table was dropped here https://github.com/18F/C2/blob/master/db/migrate/20140512190302_drop_approvers_table.rb, but model was not removed

**Comment by jessieay** [comment]
Guessing we should link to this somewhere. Suggestion on where?

**Comment by afeld** [comment]
The [overview](https://github.com/18F/C2/blob/master/doc/overview.md) page is probably the most relevant, but that page might be large enough now that we should split it up (not a blocker).

**Comment by afeld** [comment]
* [ ] Embed the image in an existing/new Markdown doc
* [ ] Include a note about how it was created (and thus, how it can be regenerated)

Otherwise, looks good! :ship:

**Comment by jessieay** [comment]
@afeld 

Diagram embedded at cc6d8c13cac338a7b3d3b4d9d9cebb610613fedc
Generation of diagram explained at e23cb2680977498d1bc36c380e30cf0cff916af6

**Pull request merged**
