### PR TITLE
Create Cancellation Notification Email (read before merge)

### PR DESCRIPTION
**Pull request by rememberlenny**
# Note

This contains https://github.com/18F/C2/pull/1011

# Test

[http://localhost:5000/rails/mailers/cancellation_mailer/cancellation_notification](http://localhost:5000/rails/mailers/cancellation_mailer/cancellation_notification)

# Visual 

screen shot 2016-03-04 at 11 56 19 am

### CODE REVIEW

**Comment by jessieay** [comment]
@rememberlenny nice, you want me to QA on dev or was that done already? We haven't been doing much QA with these emails but since deploying seems like easiest way to see them in an inbox, might make sense to start

**Comment by rememberlenny** [comment]
@jessieay Yes please! I am done with all the PR-ed emails.

I've been QAing the markup via email testing services (Litmus and Mailchimp). Testing how they actually render would be good.

**Comment by jessieay** [comment]
Emails look good on staging:

Cancellation confirmation: (https://trello.com/c/AFFZis6N) - this looks good although it doesn't appear that it was updated in this PR? Maybe include trello links in future PRs so we know which PR is for which. SO much going on! :hear_no_evil: 

screen shot 2016-03-06 at 11 07 54 am

Cancellation notification: (https://trello.com/c/OxEDUCHr/132-19-email-conversion-requester-cancelled-by-someone-else)

screen shot 2016-03-06 at 11 07 45 am

**Comment by rememberlenny** [comment]
https://trello.com/c/OxEDUCHr/132-19-email-conversion-requester-cancelled-by-someone-else

**Pull request merged**
