### PR TITLE
New details page: Activity/Timeline card

### PR DESCRIPTION
**Pull request by yozlet**

### CODE REVIEW

**Comment by yozlet** [comment]
Currently still missing the "request modified" update. I have all the code for it, just having a bit of trouble getting it all connected...

**Comment by rememberlenny** [comment]
Looks good!

**Comment by rememberlenny** [comment]
@yozlet Can you submit the Request Modified update seperately?

**Comment by rememberlenny** [comment]
I merged this because the ProposalController was erroring out on other branches due to the Activity partial needing `history`. 

I moved the corresponding Trello card over and create a new one with the remaining task.

https://trello.com/c/yhINmOug/399-details-activity-timeline-request-modified-time-part-2

@yozlet

**Pull request merged**
