### PR TITLE
Building updates per support ticket request #152

### PR DESCRIPTION
**Pull request by phirefly**

### CODE REVIEW

**Comment by pkarman** [comment]
:+1:  -- waiting for CI to restart before merging

**Comment by phirefly** [comment]
It occurs to me that if a request that used the previously used versions of this building, one wouldn't be able to modify the request without problems. Thoughts?

**Comment by pkarman** [comment]
don't our JSON fields allow arbitrary input? I know they do for vendor.

**Comment by phirefly** [comment]
I will test this....

**Pull request merged**
