### PR TITLE
do not limit text fields to 255 chars

### PR DESCRIPTION
**Pull request by pkarman**
Trello: https://trello.com/c/xC3qGgZL/138-gsa18f-procurements-limited-to-255-chars

### CODE REVIEW

**Comment by jessieay** [comment]
should we do this for `ncr_work_orders` while we're here?

**Comment by pkarman** [comment]
maybe? we just haven't had any bug reports about that client type because all the fields (except `project_title`) are populated via dropdown menus, not text boxes. I.e. there aren't free-form inputs on the NCR form.

**Comment by pkarman** [comment]
@jessieay since this represents an actual bug, as opposed to a hypothetical one, let's move forward with this fix and change the NCR case if/when it is a problem.

**Comment by jessieay** [comment]
@pkarman sounds good. only update I'd make before merging is to make the migration reversible.

**Comment by pkarman** [comment]
@jessieay good call. I guess the `change` method doesn't handle `change_column` very well.

Fixed in 516bbc5

**Comment by jessieay** [comment]
@pkarman :+1:

**Pull request merged**
