### PR TITLE
[Delivers #101461556] Add an optional reason when adding an observer

### PR DESCRIPTION
**Pull request by yozlet**
The same functionality as previously implemented by #573, but this time on top of the user roles work in #575 (on which this PR is dependent, so that needs to be merged first)

### CODE REVIEW

**Comment by afeld** [comment]
@yozlet Mind merging `master`?

**Comment by bipartisanMas0n** [comment]
When the advocate / doctor requires assistance providing antipsychotic medication to a patient, whom is under involuntary detainment and who is also marked 'GRAVELY DISABLED" while being held inside the Mental Health Facility; this person is a prime victim on a very tiny hitlist, personally hand-crafted American psychological paper-torture. Paper cuts hurt, especially when you use paper documents to cut a target down to size, by punishing them with antipsychotic medication, and depriving them of outside contact as well as fresh air; keeping patients in hallways for weeks is corrupt abusive mental-torture.

**Comment by bipartisanMas0n** [comment]
A doctor within the walls of mental hospitals have a long history of neglect and abuse toward patients. This would trigger an advocates sense of worry and allows them to supply proper documentation, to combat and protect a patients' rights as soon as contacted by phone, or some other form of contact takes place to inform the patients' advisor of the recent detainment.
 
This is all too often the results of which have permanent damage to patient, or it also may be the cost of the patients' life, if there is no resources provided for the patients' rights to begin with, the diagnoses is automatically corrupting itself by lack of providing a patient with admition papers / packets of instructional resources and also providing them with printed paper copy of each medication to be administered by a physician, immediately dated in the patient chart, during the face-to-face consultation / evaluation with the doctor who forced is pre-planning a full evaluation of the patients' health while planning his / her prayer for relief document

**Comment by bipartisanMas0n** [comment]
Imagine an 18 year old youth being wheeled into an unknown located hospital, being carted in blind to her "moral-murder-scene" that was to take place. Her life is in the hands of the two EMT's wheeling her in, as she lays on her back relaxed and curious, but mute to the abuse she had withstood at a PHF facility for the few days before the EMT's came for her body...

This facility was a picture-perfect slaughter-hall designed by a sadistic staff and their punishment scheme for money from the SSA. Innocent patients die their, but not before they were raped and tortured by medication-addiction to advance aging and degeneration of the mental motor skills of a patients' mind. These staff members out number patients by size and intimidation factors coming into play with the male-nurse staff and the female medication dispenser nurses.

Black men towering over 5'3 young femals and little tiny nurses with needles and cups full of pills, each sent in a series of time-sets based on their "chart" they will force cocktail-cups full of random pills on the weakened female by threatening them with force-shots of unknown meds if their is any retaliation; verbal or physical.

Advocates protect patients, and are highly trained to understand rights of the people so that this doesn't take place. But sometimes people slip through our fingertips, and we don't even know they needed help; this is where a power of attorney is brick-layered into a protection document, naming a family or friend available to make decisions on the patients behalf if the advocate advisor cannot be present to make the decisions as patient advisor.

**Comment by bipartisanMas0n** [comment]
Standard protection / security layering in advocates' cake tiers.

**Comment by yozlet** [comment]
Master merged, tests pass, but I'm not sure the story is complete. Have added [a note to the story](https://www.pivotaltracker.com/story/show/101461556) in Tracker.

**Comment by yozlet** [comment]
@phirefly: For some reason GitHub is claiming 2 Code Climate issues, but CC itself seems to disagree, so we're choosing to believe CC on this.

**Comment by annalee** [comment]
:+1: not sure why codeclimate is throwing an error; there's no error when you click through. :shipit:

**Pull request merged**
