### PR TITLE
Add observers to json work order output.

### PR DESCRIPTION
**Pull request by l3iodeez**
Addresses this issue from pivotal: https://www.pivotaltracker.com/n/projects/1149728/stories/106791568

### CODE REVIEW

**Comment by pkarman** [comment]
This is a great start, thanks @l3iodeez.

I'd like to see some more test coverage that actually includes one or more observers in the response. Care to take another pass? If you're out of tuits, I'm happy to merge as-is and just leave the PT story open.

**Comment by jessieay** [comment]
Hey @l3iodeez - just following up on Peter's comment. Do you think you will have time to take another pass at this?

**Comment by l3iodeez** [comment]
I should be able to take another look today or tomorrow sorry for the delay!

**Comment by l3iodeez** [comment]
I added a trait :with_observers to the :ncr_work_order factory, and used it to provide test coverage. Let me know if this works or I should do something else.

**Comment by pkarman** [comment]
@l3iodeez this looks perfect. Just need to update your branch from master to resolve conflicts.

Thanks!

**Comment by jessieay** [comment]
Rebased and opened a new PR with these commits at https://github.com/18F/C2/pull/891

**Pull request closed without merging**
