### PR TITLE
Observers design tweaks

### PR DESCRIPTION
**Pull request by micahtaylor**

### CODE REVIEW

**Comment by phirefly** [comment]
@micahtaylor This PR doesn't look like new code. Am I missing something?

**Comment by phirefly** [comment]
Also, please post some screengrabs for design changes if possible. Thx!

**Comment by micahtaylor** [comment]
Updated from master. Screenshots below.

screen shot 2016-07-13 at 10 11 41 am
screen shot 2016-07-13 at 10 11 06 am

**Comment by micahtaylor** [comment]
https://trello.com/c/IstY2hno/551-observers-design-tweaks

**Comment by phirefly** [comment]
@amberwreed gives 👍

**Pull request merged**
