### PR TITLE
Hide "needs review" section when no proposals need review

### PR DESCRIPTION
**Pull request by jessieay**
* For https://trello.com/c/XM2HDJ32

### CODE REVIEW

**Comment by jessieay** [comment]
There is definitely some overlap between this and https://github.com/18F/C2/pull/883/files

**Comment by pkarman** [comment]
@jessieay should we wait till #883 is merged to see if there are conflicts?

**Comment by pkarman** [comment]
code looks good to me -- I like that we are giving elements ID attributes and using those rather than page placement for identification.

**Comment by jessieay** [comment]
now that I re-review #883, I see that none of the specs Yoz added are in the spec file modified in this PR (`sort_index_spec.rb`) -- perhaps some of the specs I wrote here should be moved to `spec/features/proposals/index_spec.rb`, which he did modify. I will talk with him today re: his availability to update #883. If he can't do it today, we should probably merge this first and then merge his later.

**Comment by pkarman** [comment]
ok on c2-dev

**Pull request merged**
