### PR TITLE
[HOLD] [Delivers #79556070] Mandrill SMTP config

### PR DESCRIPTION
**Pull request by pkarman**
Story: https://www.pivotaltracker.com/story/show/79556070

### CODE REVIEW

**Comment by pkarman** [comment]
Testing this requires setting environment variables on the cf app target (staging, production, etc).

**Comment by afeld** [comment]
Looks good! Sending a calendar invite to pair on the domain/Mandrill side. Do you have AWS access?

**Comment by afeld** [comment]
Also, thoughts about whether we need distinct sender emails for dev/staging/production?

**Comment by afeld** [comment]
Worked on dev successfully! Going to wait to merge until right before we're ready to deploy so we don't get confused by the new environment variables.

Before merge (@pkarman, mind grabbing this?):

* [ ] Allow a `NOTIFICATION_REPLY_TO` email to be specified, so that we can have replies go to our GMail inbox until we get the incoming replies working through Mandrill

Before deploy:

* Set `NOTIFICATION_FROM_EMAIL `
    * [ ] dev
    * [ ] staging
    * [ ] prod
* Change `SMTP_USERNAME`
    * [ ] dev
    * [ ] staging
    * [ ] prod
* Change `SMTP_PASSWORD`
    * [ ] dev
    * [ ] staging
    * [ ] prod

**Comment by afeld** [comment]
Oooh, wait, I only saw the emails come through to my personal address...we probably have the same issues here as we did with sending from MailChimp. Will follow up with Ted.

**Comment by pkarman** [comment]
@afeld thanks for making checklists. `NOTIFICATION_REPLY_TO` added in 50c6f22

**Comment by phirefly** [comment]
Validated this on staging and email sends are looking great. Let's wait to merge this until immediately before deploy, early week of 10/12. 

Added pre-deploy tasks to the sprint milestone: https://www.pivotaltracker.com/story/show/105353272

**Pull request merged**
