### PR TITLE
[WIP] Remove leading zeroes from date strings

### PR DESCRIPTION
**Pull request by yozlet**
Fixes strings like `04/04/16` (in the activity panel) and `April 07, 2016` (in the summary panel). 

EDITED:
After the above, @dogweather and I migrated the `strtftime` formats to `config/initializers/date_format.rb`

### CODE REVIEW

**Comment by dogweather** [comment]
_Thinking about refactoring these out into date formats_.

screen shot 2016-06-01 at 4 35 53 pm

http://railscasts.com/episodes/31-formatting-time?view=asciicast

**Comment by dogweather** [comment]
I checked out this branch to try refactoring these, but couldn't make my changes visible. (?)

**Comment by yozlet** [comment]
Ooh, didn't know about this. OK, I'll make those changes.

**Comment by rememberlenny** [comment]
@yozlet Is this good to go?

**Comment by yozlet** [comment]
@rememberlenny Nope, not yet - sorry!

**Comment by yozlet** [comment]
@rememberlenny OK, now. 😄

**Comment by dogweather** [comment]
This fell through the cracks and now there's a merge conflict

@yozlet you should feel free to just merge this yourself once someone's given a thumb's up. Need help resolving the conflict?

**Comment by rememberlenny** [comment]
Looks good!

**Pull request merged**
