### PR TITLE
C2 content edits

### PR DESCRIPTION
**Pull request by phirefly**
Paired with @amberwreed on content changes to modals and flash messages.

@amberwreed please review and merge if everything looks good. Thank you!

### CODE REVIEW

**Comment by rememberlenny** [comment]
@phirefly Can you update your branch and catch up to master?

**Comment by amberwreed** [comment]
Looks good to me! _Looking for a merge button._

**Comment by rememberlenny** [comment]
@amberwreed We need @phirefly to do a little more code updates!

**Comment by phirefly** [comment]
Thanks. I will resolve conflicts + merge

**Pull request merged**
