### PR TITLE
Added check for double approval

### PR DESCRIPTION
**Pull request by nickbristow**
Needs tests and review

### CODE REVIEW

**Comment by afeld** [comment]
@nickbristow My instinct is that we want to handle this at the model level. @cmc333333 What do you think about adding an no-op `:approve` action for the `:approved` state in the `ThreeStateWorkflow`. Also `:reject` for `:rejected`, etc... basically ignoring repeat actions.

https://github.com/18F/C2/blob/master/app/models/concerns/three_state_workflow.rb

**Comment by nickbristow** [comment]
@afeld that was the other way i thought about doing it, but should the user get a different message then?

**Comment by afeld** [comment]
Maybe we can handle it in a more generic way, saying that "if the previous state and new state are the same, just say 'you already `#{action}`d this proposal'".

**Comment by afeld** [comment]
..which would also cover rejection, etc.

**Comment by nickbristow** [comment]
@afeld ok, one sec.

**Comment by cmc333333** [comment]
@afeld There's one use case that is kinda tricky, though: what if a rejected approval gets an "approve" message or vice versa?

I'm more inclined to say "you've already chosen. you can choose no more"

**Comment by afeld** [comment]
:+1:

**Comment by phirefly** [comment]
Per @cmc333333's comment, does this mean we need an `unless approval.status == 'pending'` to cover both rejected and approved?

**Comment by cmc333333** [comment]
:+1:

**Pull request merged**
