### PR TITLE
[Delivers #97242150] disallow assigning requester as approver and vice-versa

### PR DESCRIPTION
**Pull request by pkarman**
Story: https://www.pivotaltracker.com/story/show/97242150

Testing:

* create new NCR work order
* verify you are not listed amongst the possible approvers

### CODE REVIEW

**Comment by jessieay** [comment]
merge conflicts on this one

**Comment by pkarman** [comment]
merged ok now @jessieay

**Comment by jessieay** [comment]
This looks good! One high-level question I have is about how this relates to other use cases. 

I know we don't allow approver assignment for 18F procurements, but I imagine there will be other use cases in the future that have a dropdown similar to NCR work orders. Since this is the case, would it make sense to define `ineligible_approvers` on `proposal` or some other shared logic so that the concept of not allowing a requester to approve is automatically extended to future use cases?

**Comment by pkarman** [comment]
@jessieay fair point. I have moved `.ineligible_approvers` to the Proposal model.

**Comment by jessieay** [comment]
looks good! merge conflict. once that's fixed, will QA!

**Comment by pkarman** [comment]
@jessieay merge fixed

**Comment by jessieay** [comment]
Before:

screen shot 2015-11-17 at 1 00 37 pm


After:

screen shot 2015-11-17 at 1 05 01 pm


MERGING

**Pull request merged**
