### PR TITLE
Doorkeeper oauth fix

### PR DESCRIPTION
**Pull request by pkarman**
see https://trello.com/c/5p8smp6E/596-oauth-authorize-action-broken

### CODE REVIEW

**Comment by dogweather** [comment]
Hey Peter, I'm wondering why we're running an oauth provider — https://trello.com/c/5p8smp6E/596-oauth-authorize-action-broken#comment-577edc9cddb85edf6633cdaf

**Comment by jessieay** [comment]
@pkarman rebase?

**Comment by pkarman** [comment]
hm. I rebased an hour ago. Will try again.

**Comment by pkarman** [comment]
@jessieay quick! while it's up to date! :)

**Comment by dogweather** [comment]
@pkarman if it's ready to go and reviewed by someone, please go ahead and merge your own code — we've switched to that workflow: After getting an "ok", each of us is free to merge the PR and delete the branch.

**Comment by jessieay** [comment]
WOO! LGTM

**Pull request merged**
