### PR TITLE
Do not show "reason" text when no reason for adding observer

### PR DESCRIPTION
**Pull request by jessieay**
* Previously showed "Reason: " when no reason

https://trello.com/c/jYGT0z5J

### CODE REVIEW

**Comment by pkarman** [comment]
false error with `Capybara::Poltergeist::DeadClient` -- I restarted CI.

**Comment by pkarman** [comment]
looks good. waiting on CI to merge.

**Comment by jessieay** [comment]
@pkarman we are :green_heart:

**Comment by rememberlenny** [comment]
Look good

**Pull request merged**
