### PR TITLE
Ability to see observers goes away after approval is complete

### PR DESCRIPTION
**Pull request by istanfield09**
[Relevant Pivotal Tracker story.](https://www.pivotaltracker.com/story/show/99172282) Let me know what you think. Thanks!

### CODE REVIEW

**Comment by afeld** [comment]
I'm actually not sure that this story is still relevant... @phirefly can you confirm?

**Comment by bipartisanMas0n** [comment]
This can be 100% confirmed by Dr. Markee Cuevas

**Comment by bipartisanMas0n** [comment]
http://pedersen-advocate-cave.simdif.com

**Comment by phirefly** [comment]
Sorry about that, @istanfield09. We used to have links that went to a separate Observers page. Since pulling this page into the detail page, this story became irrelevant. I've deleted the Pivotal story.

**Comment by istanfield09** [comment]
No worries! : )

**Pull request closed without merging**
