### PR TITLE
tweek ES retry logic

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by jessieay** [comment]
is there an explanation of the reason for this change? or future "us" more than anything else...

**Comment by pkarman** [comment]
we are still seeing occasional failures at CircleCI so wanted to try to improve debugging of why that is happening.

**Comment by pkarman** [comment]
@jessieay let me know if that rationale isn't detailed enough.

**Comment by pkarman** [comment]
example: https://circleci.com/gh/18F/C2/4010

**Pull request closed without merging**
