### PR TITLE
Add code of conduct to CONRTIBUTING.md

### PR DESCRIPTION
**Pull request by jessieay**
* Also link to setup docs
* https://www.pivotaltracker.com/story/show/104755446

### CODE REVIEW

**Comment by jessieay** [comment]
what do I do to the pivotal tracker story to indicate that a PR for the chore was created? I linked to it for now but imagine it might need a status change?

**Comment by pkarman** [comment]
@jessieay the https://github.com/18F/C2/blob/master/doc/team_practices.md doc should detail the workflow for PT and GH. Please patch where clarification would be helpful.

**Comment by jessieay** [comment]
@pkarman thanks for the link! I am not used to having a separate file for team practices so I was looking for the info in `Contributing`

**Comment by jessieay** [comment]
@pkarman this is ready for review - not sure why code climate hasn't finished running yet, but I opened the PR on Friday....seems like a bug code climate bug

**Comment by pkarman** [comment]
looks great, thanks @jessieay .

**Pull request merged**
