### PR TITLE
switch from cf-blue-green to autopilot for zero downtime deploys

### PR DESCRIPTION
**Pull request by pkarman**
tested successfully on c2-dev and c2-staging

### CODE REVIEW

**Comment by jessieay** [comment]
Should we update The Docs to reflect this change? https://github.com/18F/C2/blob/master/doc/production.md#deploying

**Comment by pkarman** [comment]
@jessieay good catch! fixed in e80cc1a

**Comment by pkarman** [comment]
@jessieay test failure is just the Ghost in the Machine

**Comment by jessieay** [comment]
:+1:

**Pull request merged**
