### PR TITLE
bump ruby version to 2.2.5

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by rememberlenny** [comment]
@pkarman Are there any concerns around this? I take it the tests are failing for the very purpose of the PR.

**Comment by dogweather** [comment]
This is probably not the current issue, but AFAIK one shouldn't use `migrate` to set up the database:

> bundle exec rake db:create db:migrate

It's not guaranteed to work. And it generally doesn't in a mature app because of sync errors between the current code and the old migration state. Instead,

> bundle exec rake db:setup

is the right way to do it. It creates the database schema via `db:schema:load`, which is guaranteed to be correct.

**Comment by dogweather** [comment]
I'm having a whack at it.

**Comment by dogweather** [comment]
That commit fixes the database install. Now seeing the same error further down at the `rspec` invocation.

**Comment by dogweather** [comment]
The core problem is a `rubygems` incompatibility. Running `gem update --system` on the test server resolves it.

**Comment by pkarman** [comment]
This upgrade is for cloud.gov where the default buildpack has now stopped supporting Ruby 2.2.3.

This is actually already deployed on stage and prod, as it was necessary to get out the fix on Friday 4/29 for the feedback spam issue.

**Comment by dogweather** [comment]
Ok, thanks. Do we still need to merge this into master?

**Comment by pkarman** [comment]
definitely, once tests pass. otherwise master cannot be deployed to cloud.gov

**Comment by rememberlenny** [comment]
Going to merge this so we can push to cloud.gov

**Pull request merged**
