### PR TITLE
fix DOM structure where then are zero completed proposals

### PR DESCRIPTION
**Pull request by pkarman**
A small HTML nit: fix the empty list DOM structure to be consistent for all tables.

### CODE REVIEW

**Comment by jessieay** [comment]
looks good! screenshots would be helpful for this type of change in future :ship:

**Comment by pkarman** [comment]
div-close-before
div-close-after

**Comment by jessieay** [comment]
yay screenshots - looks much better! what do you say we merge this puppy without QA?

**Comment by pkarman** [comment]
:+1:

**Comment by jessieay** [comment]
Feels so good to be bad - merging!

**Pull request merged**
