### PR TITLE
[Delivers #99002900] don't show all Proposals to admins / client admins

### PR DESCRIPTION
**Pull request by afeld**
...though they can still visit them directly.

* [ ] Deploy branch to test on dev/staging

### CODE REVIEW

**Comment by cmc333333** [comment]
This removes those proposals from search, too. Is that the intent?

**Comment by afeld** [comment]
Hmm, good point. Maybe it would make more sense to think of this as a filter rather than a Policy?

**Comment by afeld** [comment]
...and by "this" I mean "the intended behavior".

**Comment by afeld** [comment]
Thinking we'll go about this a different way.

**Pull request closed without merging**
