### PR TITLE
Small Tabular Data refactors

### PR DESCRIPTION
**Pull request by jessieay**
* Move `config_for_client` method into its own class

### CODE REVIEW

**Comment by jessieay** [comment]
hmmm trying to make the method smaller to fix CC failure. Tough! but working on it. otherwise, this is ready for review

**Comment by jessieay** [comment]
ok code climate should be happy now

**Comment by pkarman** [comment]
+1 looks good.

**Comment by pkarman** [comment]
QA'd on c2-dev. No regressions observed.

**Pull request merged**
