### PR TITLE
[Delivers #89169198] split observers and requester from Approval model

### PR DESCRIPTION
**Pull request by afeld**
`Approval`s no longer have a `role` – there is an equivalent `Observation` model, and a `requester_id` on the `Proposal` directly. These were the minimum required changes...I'll do some other cleanup in a follow-up PR.

### CODE REVIEW

**Comment by cmc333333** [comment]
Looks good to me. Relevant: master now include another instance of `observers` in `lib/dispatcher.rb`

Otherwise, I'd be happy to merge

**Comment by afeld** [comment]
> master now include another instance of `observers` in `lib/dispatcher.rb`

Sorry, I don't follow? The model is called `Observation`, so there shouldn't be any naming conflict.

**Comment by cmc333333** [comment]
Sorry, I meant `observing`. https://github.com/18F/C2/blob/master/lib/dispatcher.rb#L93 was added after you made your last commit, I think, so the tests aren't failing, but that line refers to a scope that's deleted in this PR.

**Comment by afeld** [comment]
Updated!

**Comment by cmc333333** [comment]
Makes sense to me, as does the Rspec tweak. @phirefly this may affect your PR. Will merge in the morning unless you see something else

**Comment by afeld** [comment]
can haz merge?

**Comment by cmc333333** [comment]
/me is defeated by the cute kitty

**Pull request merged**
