### PR TITLE
[Delivers #96974108] only have single budget approver for BA61

### PR DESCRIPTION
**Pull request by afeld**
@phirefly Not positive I interpreted the story correctly...mind confirming?

* [ ] Switch `NCR_BA61_TIER2_BUDGET_MAILBOX` to `NCR_BA61_BUDGET_MAILBOX` on servers

### CODE REVIEW

**Comment by afeld** [comment]
Specifically:

* Are there any cases where they *would* want the Tier 1 *and* Tier 2 approvers for BA61?
* Should we still refer to the latter as "Tier 2", or just "budget"?

**Comment by afeld** [comment]
From @phirefly:

If it's BA61 and it has org code `P1122021 – (192X,192M) WHITE HOUSE DISTRICT`, then only use the Tier 2 mailbox. Otherwise use both Tier 1 and Tier 2.

**Comment by cmc333333** [comment]
Lots of special cases there. Is it time for a rules engine?

**Comment by cmc333333** [comment]
To be clear - there are additional changes needed w/ the logic before this should be merged, right?

**Comment by afeld** [comment]
Hopefully just what I listed above, yeah.

**Comment by afeld** [comment]
> Is it time for a rules engine?

Not sure that it's *that* complicated yet, but would be curious to see what you have in mind.

**Comment by afeld** [comment]
Replaced by #397.

**Pull request closed without merging**
