### PR TITLE
Add suggestions in troubleshooting section of setup for when user has…

### PR DESCRIPTION
**Pull request by rachelylim**
… rbenv and foreman command is not found.

### CODE REVIEW

**Comment by jessieay** [comment]
Hey @rachelylim ! 

Thank you for the contribution. I think these are great tips generally - but I am not sure that they belong in this codebase since not everyone working on this will be using rbenv. 

My reasoning is this: If we start adding setup instructions for all varieties of dev setups, our setup instructions could get quite long / detailed. In general, I try to keep anything that is specific to my dev environment out of the codebase. 

All that being said, if this is as true pain point for a large # of people setting up C2, then it probably does make sense to include this information in the README. So I will keep this PR open for others to weigh in on!

**Comment by pkarman** [comment]
I'm inclined to accept this, as a helpful hint. I don't use rbenv, but I don't mind seeing this here, and it might help the next person.

If/when the doc gets too unwieldy with lots of dev-tool-specific notes, we could start a FAQ doc. We aren't there yet, imo.

+1 to merge

**Comment by pkarman** [comment]
Thanks @rachelylim !

**Comment by rachelylim** [comment]
@jessieay @pkarman Thanks for considering my suggested contribution! Glad it was somewhat useful!

**Pull request merged**
