### PR TITLE
add explicit buildpack so that Ruby 2.2.3 is supported on cloud.gov

### PR DESCRIPTION
**Pull request by pkarman**
this is necessary until 18F CF buildpacks are updated.

### CODE REVIEW

**Comment by afeld** [comment]
Maybe worth adding a comment? Is there an issue or anything we can link to?

**Comment by pkarman** [comment]
https://github.com/18F/cloud-foundry-notes/commit/6b823c69eadf4128b906b9abde8d1f9e82b05817

**Comment by jessieay** [comment]
LGTM. This is a case where a code comment might make sense because this is something we can remove at a later date when it is no longer needed :ship:

**Comment by pkarman** [comment]
thanks for reviews. I added a comment about why the buildback url is explicit.

**Pull request merged**
