### PR TITLE
[Delivers #99713258] Indicate significance of asterisk in form. 

### PR DESCRIPTION
**Pull request by phirefly**
Also Removed asterisk from the Work Orde field since it is not required

screen shot 2015-10-28 at 3 49 50 pm

### CODE REVIEW

**Comment by jessieay** [comment]
Code looks good. 

Are there any other fields that are required in the form but not required via ActiveRecord that we should address while we are here?

**Comment by jessieay** [comment]
ps - love the screenshot in the PR description. So helpful!

**Comment by pkarman** [comment]
Given the scope of this story, I'd be inclined to merge as-is and if we discover other required/not-required fields later, open separate stories for them. +1 to merge

**Comment by pkarman** [comment]
@phirefly thoughts on scope?

**Comment by afeld** [comment]
> I'd be inclined to merge as-is and if we discover other required/not-required fields later, open separate stories for them

:+1:

**Comment by afeld** [comment]
https://www.pivotaltracker.com/story/show/82418236

**Comment by afeld** [comment]
* [ ] Add same note to Procurement form (maybe make a partial?)

**Comment by phirefly** [comment]
Regarding scope, this was a small thing that I noticed when doing a walkthrough with new folks. Someone asked me if the field was required because of the asterisk and realized it shouldn't be there since not everyone has a work order. Afaik, this is the only field that has this discrepancy.

Happy to have this merge and adding a task for the Procurement form here: https://www.pivotaltracker.com/story/show/99713258 (great catch, @afeld!)

**Pull request merged**
