### PR TITLE
Adding image of email synthesis

### PR DESCRIPTION
**Pull request by amberwreed**

### CODE REVIEW

**Comment by jessieay** [comment]
thoughts on giving this a simpler name?

**Comment by amberwreed** [comment]
Giving what a simpler name? Simpler file name?

On Tue, Jun 21, 2016 at 12:05 PM, Jessie A. Young <notifications@github.com>
wrote:

> thoughts on giving this a simpler name?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/C2/pull/1362#issuecomment-227539601>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AM8pSK3ThIpqAsaVpPMvr1nYayjO_NLDks5qODXogaJpZM4I64CZ>
> .
>



-- 
-------------------------
*Amber Reed*
Experience Designer
18F

**Comment by jessieay** [comment]
yes sorry for lack of specificity- file name!

**Comment by amberwreed** [comment]
Renamed and added new images but I no longer have the option to create a
pull request. I guess it's adding the new images to the old one?

On Tue, Jun 21, 2016 at 4:31 PM, Jessie A. Young <notifications@github.com>
wrote:

> yes sorry for lack of specificity- file name!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/C2/pull/1362#issuecomment-227602948>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AM8pSFd2_gmkUbyGpDLcrxsk3eZibuXTks5qOHRogaJpZM4I64CZ>
> .
>



-- 
-------------------------
*Amber Reed*
Experience Designer
18F

**Comment by dogweather** [comment]
Hey @amberwreed you already have a Pull Request here... that's how we're commenting.

**Comment by jessieay** [comment]
hmm @amberwreed doesn't look like the image was renamed in this PR. We can hop on a call today if you want to talk it through

**Pull request merged**
