### PR TITLE
[Delivers #1072212000] Require auth in controllers by default

### PR DESCRIPTION
**Pull request by jessieay**
* Require controllers to opt out of auth rather than in
* Standardize on "before_action" rather than "before_filter"
* This is a refactor, only behavior change is slight logic change for
  admin -- redirect to home page w 302 when not logged in and trying
  to access admin rather than showing error and giving 401 status
* Story: https://www.pivotaltracker.com/story/show/107221200

### CODE REVIEW

**Comment by pkarman** [comment]
great cleanup++

I will QA

**Comment by pkarman** [comment]
QA on c2-dev:

* https://c2-dev.18f.gov/help returns a 500 error
```2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    | ActionView::Template::Error (undefined method `[]' for nil:NilClass):
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     15: </header>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     16: 
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     17: <%- if return_to %>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     18:   <%= render partial: 'shared/breadcrumb_nav', locals: {text: "Back to #{return_to[:name]}", href: return_to[:path]} %>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     19: <%- elsif display_return_to_proposal %>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     20:   <%= render partial: 'shared/breadcrumb_nav', locals: {text: "Back to Proposal", href: proposal_path(params[:id])} %>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |     21: <%- elsif display_return_to_proposals %>
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |   app/views/layouts/_communicart_header.html.erb:18:in `_app_views_layouts__communicart_header_html_erb___3775816813242501189_70353931452160'
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |   app/views/layouts/application.html.erb:19:in `_app_views_layouts_application_html_erb___1762116253662135690_70353931157620'
2015-11-18T09:23:11.48-0600 [App/0]      OUT 15:23:11 web.1    |   app/views/layouts/help.html.haml:8:in `_app_views_layouts_help_html_haml__212339050829605541_70353930606760'
```

**Comment by jessieay** [comment]
@pkarman good catch! will update now

**Comment by jessieay** [comment]
@pkarman looks like that error occured because `return_to` is undefined in `app/views/layouts/_communicart_header.html.erb` -- and I am not able to reproduce it locally. Is it possible that error was unrelated to this PR?

**Comment by pkarman** [comment]
I can no longer duplicate this. :+1: to merge

**Pull request merged**
