### PR TITLE
Add Entry for deleted attachments in activity feed

### PR DESCRIPTION
**Pull request by nickbristow**
## Ready for review/Merging

c2

### CODE REVIEW

**Comment by nickbristow** [comment]
c2

**Comment by nickbristow** [comment]
https://trello.com/c/WY3UHJ0T/503-removing-an-attachment-from-a-request-deletes-it-from-the-history-is-this-how-you-intended-for-it-to-work

**Comment by nickbristow** [comment]
I need to add a test to this.

**Comment by rememberlenny** [comment]
Looks good!

**Pull request merged**
