### PR TITLE
[Delivers #107725118] purchase text changes

### PR DESCRIPTION
**Pull request by yozlet**
From @annalee & me:

 * Changes the language used in proposal views  to be more generic in referring to step types
 * Adds the Approver role in the step display at the top of the proposal page
 * Shows correct text for step action in email notifications
 * Adds some initial, bare-bones page objects for testing the proposal page

### CODE REVIEW

**Comment by pkarman** [comment]
the `site_prism` gem seems really helpful, and magical.

this looks really great. I will QA, if you can provide any guidance on particular things to look for.

**Comment by yozlet** [comment]
@pkarman Thank you! Main things to check are all in 18F procurements:

 * Proposal detail page, status section at the top, listing the two steps, should show "(Approver)" next to email address of approver (first step) and "(Purchaser)" next to purchaser (second step)
 * Email notification to Purchaser should have a "Mark as Purchased" button as opposed to an "Approve" button.

**Comment by yozlet** [comment]
... also, check visual alignment of text and icons in the proposal status section of the detail page.

**Comment by yozlet** [comment]
OK, putting down the "Rename" tool in RubyMine and backing away (for the rest of this PR, anyway)

**Comment by pkarman** [comment]
looks good on c2-dev
screen shot 2015-12-03 at 12 34 41 pm
screen shot 2015-12-03 at 12 37 30 pm

**Comment by pkarman** [comment]
screen shot 2015-12-03 at 12 38 29 pm

**Pull request merged**
