### PR TITLE
Fix ncr_organization/org_code labelling

### PR DESCRIPTION
**Pull request by yozlet**
The "Org Code" label wasn't showing up properly in the new detail page. Also removed the `org_code` key, because AFAIK we're not using it.

### CODE REVIEW

**Comment by rememberlenny** [comment]
@yozlet Good to go?

**Comment by phirefly** [comment]
@yozlet Does this mean that `org_code` is in use?
https://github.com/18F/C2/blob/master/app/decorators/ncr/work_order_decorator.rb#L87

I might be misunderstanding the removal of this attribute, but I think this bit of code would call that, wouldn't it?

**Comment by yozlet** [comment]
@phirefly: Argh, yes, you're right. Sorry about that. Will fix.

**Comment by yozlet** [comment]
Closing this in favour of #1327.

**Pull request closed without merging**
