### PR TITLE
fix wording of Comment comment

### PR DESCRIPTION
**Pull request by afeld**
@cmc333333 Mind double-checking this is what you meant?

### CODE REVIEW

**Comment by cmc333333** [comment]
Hrm. No, I meant "future" -- where a "future" approver is one who hasn't seen the proposal yet.

**Comment by afeld** [comment]
Hmm, `currently_awaiting_approvers` is minus both...updated.

**Comment by cmc333333** [comment]
Right `currently_awaiting_approvers` should be all actionable approvers -- those who can take action now. That gets added to the `approved` approvers, which should be all approvers who took action in the past. All that's missing, then, is the future approvers.

This is one of the multiple places where this kind of "subscriber" logic is being calculated -- each time the logic is ever so slightly different.

**Comment by afeld** [comment]
Oh. Derp.

Thanks!

**Pull request closed without merging**
