### PR TITLE
Create email templates for emails to step users after step complete

### PR DESCRIPTION
**Pull request by jessieay**
* one template for steps that need to be re-reviewed, one for steps
  that do not
* re-reviewed: https://trello.com/c/jWfjbfxD
* not re-reviewed: https://trello.com/c/jWfjbfxD

Needs re review:

screen shot 2016-03-01 at 1 38 03 pm

screen shot 2016-03-01 at 1 37 33 pm

Does not need re-review:

screen shot 2016-03-01 at 1 29 14 pm

screen shot 2016-03-01 at 1 29 08 pm

### CODE REVIEW

**Comment by pkarman** [comment]
@jessieay looks ok.

under what conditions would the `modifier` ever legitimately be a `NullUser` ?

**Comment by jessieay** [comment]
@pkarman if someone modified it via Rails console there would be no `current_user`, I believe.

**Comment by jessieay** [comment]
@pkarman if the `modifier` argument were non-optional I'd assume we would always have one. I think it is optional because of the rails console case.

**Comment by pkarman** [comment]
@jessieay :+1:

**Pull request merged**
