### PR TITLE
improve availability of production

### PR DESCRIPTION
**Pull request by afeld**
I've been seeing the app hanging and `502 Bad Gateway` errors when trying to load the site a few times recently, and yesterday at 5pm ET the app was `down` for no particular reason. After looking at the top graph in New Relic, I believe the problem is a memory constraint during garbage collection.

screen shot 2015-10-15 at 5 37 56 pm

There may be other issues that are causing us to consume that much memory, but increasing the instance capacity and having a backup instance in production should at least keep it from crashing. See the individual commits for more explanation of the changes.

### CODE REVIEW

**Comment by jessieay** [comment]
Since we can change this with ENV var value changes rather than code, is it worth trying to change the env var vals first and then hard-coding defaults later if it turns out to be a good change?

**Comment by afeld** [comment]
@jessieay The issue this PR is (attempting to) solve is hitting the memory limit within individual instances. By increasing the number of `instances`, we are improving availability in case one of them _does_ crash. Two `instances` means we will have twice as many server threads available, but we already had more capacity than needed, so I reduced the number to keep our capacity about equivalent to what it was before. Does that make sense?

> is it worth trying to change the env var vals first and then hard-coding defaults

I mean, I'm kinda in favor of the "configuration as code" idea...this way we can see the history.

---

@dlapiduz Would love feedback in general!

**Comment by pkarman** [comment]
+1 to config in code. Even if we are experimenting, I like the see the version history of the experiment.

**Comment by jessieay** [comment]
@pkarman @afeld I am totally fine with that, but should we remove the `MAX_THREADS` env var since we don't appear to be using it?

**Comment by afeld** [comment]
Updated!

**Comment by jessieay** [comment]
@afeld :+1: :ship: just waiting for Code Climate to pass before merging

**Comment by jessieay** [comment]
MERGING (doesn't appear that this needs QA)

**Pull request merged**
