### PR TITLE
[Delivers #108392258] add Hakiri config

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
* [ ] Get branches to appear on https://hakiri.io/projects/e9eaa829ff32a6 (reached out to support)
* [ ] Add badge to README

**Comment by afeld** [comment]
Ready for :eyes: !

**Comment by jessieay** [comment]
this looks cool! should we add something in the docs about it?

**Comment by afeld** [comment]
Not opposed, but not sure what they would say...

**Comment by pkarman** [comment]
what are the ToS for Hakiri? When I signed up I get a message that my trial expires in 14 days.

**Comment by afeld** [comment]
I believe that Hakiri is something we've procured, so I think we're ok.

/cc @NoahKunin @monfresh https://github.com/18F/DevOps/issues/157

**Comment by NoahKunin** [comment]
@pkarman We haven't purchased Hakiri - it's free for public repositories. 

@afeld would it be easier for your work in #compliance etc. if we purchased one of these plans?

https://hakiri.io/pricing

**Comment by afeld** [comment]
> We haven't purchased Hakiri

Ah, sorry. I meant "it has been blessed by @NoahKunin."

> would it be easier for your work in #compliance etc. if we purchased one of these plans?

No difference for me. Thanks though!

**Comment by pkarman** [comment]
@afeld just to be clear before I merge this: no changes necessary to docs to reflect Hakiri account(s) needed for new devs?

**Comment by afeld** [comment]
Updated!

**Pull request merged**
