### PR TITLE
Dev admin can view proposals

### PR DESCRIPTION
**Pull request by jessieay**
* To test:
  visit admin
  click on proposals
  view-only options should be present (no edit/delete/create)

screen shot 2015-11-20 at 2 39 07 pm

### CODE REVIEW

**Comment by jessieay** [comment]
@phirefly this logic implements https://github.com/18F/C2/pull/816

But it does not have a place for "reason" or send out cancellation emails like cancelling an email through the regular UI does. Do we need that functionality? Not sure what the exact use case for this PR is

**Comment by pkarman** [comment]
@jessieay seems like maybe adding an automatic comment like "cancelled by _user_ via admin" or something?

**Comment by jessieay** [comment]
@pkarman just caught up w Raphy about this. He meant for dev admins to be able to cancel via regular UI. Going to change this to be a read-only for proposals in admin and do the editing stuff in a different PR.

**Comment by jessieay** [comment]
@pkarman ready for re-review (with new scope for story) :railway_car:

**Comment by pkarman** [comment]
looks great.

**Pull request merged**
