### PR TITLE
C2 from email address

### PR DESCRIPTION
**Pull request by pkarman**
Since our new production sender email address is *inbox@c2.18f.gov* without any human-readable name, the sender appears as 'inbox' when viewing the message. Let's make it friendlier.

### CODE REVIEW

**Comment by jessieay** [comment]
Looks great! :ship:

**Comment by jessieay** [comment]
@pkarman this is pretty small, does it still require QA?

**Comment by pkarman** [comment]
@jessieay well, I'm pretty paranoid in general, so I would probably QA it on stage. If you wanted to batch it up with another branch needing QA, merge the branches together, that might expedite.

**Comment by jessieay** [comment]
Ok, will QA this with a few others soon

**Comment by jessieay** [comment]
@pkarman is there a tracker story for this?

**Comment by jessieay** [comment]
Looks good on staging! merging 

screen shot 2015-10-20 at 2 38 15 pm

**Comment by pkarman** [comment]
there is now: https://www.pivotaltracker.com/story/show/106157368

**Pull request merged**
