### PR TITLE
Add info on blocked stories to Team Practices doc

### PR DESCRIPTION
**Pull request by jessieay**
* Stories that are not actionable should be moved to icebox
* Reference: https://18f.slack.com/archives/cap/p1446062132000076

### CODE REVIEW

**Comment by jessieay** [comment]
Want to make sure everyone sees this bc it seems like a helpful clarification for Tracker management. cc @afeld @pkarman @yozlet @annalee

**Comment by pkarman** [comment]
Do we really want to move it to the icebox straight away? Seems like a judgement call the product manager should make, since presumably they are the one who prioritized it in the first place.

Can I amend to "tag with *blocked* and assign to the product owner" as sufficient? Presumably our stand-ups are the place to bring this up, and moving it to icebox means it'll just "disappear" from the current sprint.

**Comment by jessieay** [comment]
@pkarman I created this PR based on Slack convo linked to with Raphy, so I will let him respond to your questions. Either way works for me, I just want to make sure we have the "blocked story" process documented.

cc @phirefly

**Comment by phirefly** [comment]
@pkarman I concur, partly because detail may immediately be added that will make the story actionable. How about "tag the story with `blocked` tag and assign the product manager as the owner to determine next actions"

**Comment by jessieay** [comment]
@phirefly @pkarman updated!

**Comment by pkarman** [comment]
great, thanks.

**Pull request merged**
