### PR TITLE
allow autoprefixer to handle the cross-browser placeholder styles

### PR DESCRIPTION
**Pull request by afeld**
Just something I stumbled across while working on #656.

https://github.com/postcss/autoprefixer/issues/44#issuecomment-41183918

### CODE REVIEW

**Comment by pkarman** [comment]
@afeld can you give some testing advice on this one? The code itself looks fine.

**Comment by afeld** [comment]
The quick way is checking that generated CSS rule looks the same, including all same the browser-prefixed properties. The longer way is checking that the color of the placeholder text in form fields throughout the app hasn't changed, in various browsers.

**Comment by pkarman** [comment]
before
```css
/* line 1, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control {
  /*Placeholder text color*/
}
/* line 3, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control::-webkit-input-placeholder {
  /* WebKit browsers */
  color: #777677;
}
/* line 6, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control:-moz-placeholder {
  /* Mozilla Firefox 4 to 18 */
  color: #777677;
  opacity: 1;
}
/* line 10, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control::-moz-placeholder {
  /* Mozilla Firefox 19+ */
  color: #777677;
  opacity: 1;
}
/* line 14, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control:-ms-input-placeholder {
  /* Internet Explorer 10+ */
  color: #777677;
}

/* line 19, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.alert {
  outline: none;
}

/* line 23, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.help-block {
  font-size: .75em;
}
```
after
```css
/* line 2, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.form-control::-webkit-input-placeholder {
  color: #777677;
  opacity: 1;
}
.form-control::-moz-placeholder {
  color: #777677;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #777677;
  opacity: 1;
}
.form-control::placeholder {
  color: #777677;
  opacity: 1;
}

/* line 8, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.alert {
  outline: none;
}

/* line 12, /Users/peterkarman/src/C2/app/assets/stylesheets/common/form-control.scss */
.help-block {
  font-size: .75em;
}
```

**Comment by afeld** [comment]
Looks how I expect :+1:

**Comment by pkarman** [comment]
The before/after is pretty close. Some very minor differences. Seems like older mozilla-based engines might be the only ones affected, but those are so old I don't care enough to figure out how to install one to test with.

**Pull request merged**
