### PR TITLE
86055782 ncr send email after request

### PR DESCRIPTION
**Pull request by phirefly**
Don't merge. Just posting for feedback as I finish the second part of the story. In a nutshell, adding ncr-specific logic for when to send out notification emails while allowing for a default set for Linear approvals.

Feedback welcome.

### CODE REVIEW

**Comment by afeld** [comment]
Can you give a high-level description of what you are going for here? Wondering if we might be able to generalize the logic a bit.

**Comment by afeld** [comment]
In other words, what's the User Story? :memo:

**Comment by phirefly** [comment]
Sure thing. The story is [#86055782](https://www.pivotaltracker.com/story/show/86055782): Only send an email at the first approval and last approval.

**Comment by phirefly** [comment]
Might be worth dropping the logic into a  [concern](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html).

**Comment by afeld** [comment]
Did you mean to close?

**Comment by afeld** [comment]
Moved to https://github.com/18F/C2/pull/197.

**Pull request closed without merging**
