### PR TITLE
set ClassLength max to 250 lines (default is 100)

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by jessieay** [comment]
Works for me as long as we try to keep classes on the small side! Interested in what others think

**Comment by pkarman** [comment]
feedback requested. cc/ @yozlet @annalee @afeld

**Comment by annalee** [comment]
This is fine by me! I've never been terribly fussy about class length, though.

**Comment by yozlet** [comment]
I agree with @jessieay, especially since some of our classes are longer than they should be (which we're fixing with concerns, etc.) But our classes tend to have other stuff that inflates them, especially those big `workflow` blocks. So :+1:

**Comment by afeld** [comment]
+0 on this.

**Pull request merged**
