### PR TITLE
Include cancellation reason in email

### PR DESCRIPTION
**Pull request by jessieay**
* Include reason if there is one
* Story: https://www.pivotaltracker.com/story/show/101131916

To QA: 

scenario 1:
create a proposal with an approver with a non-pending approval status (aka - approver knows about proposal)
cancel the proposal as a requester WITH a reason
email to approver SHOULD include the reason

### CODE REVIEW

**Comment by pkarman** [comment]
Looks good. Nice use of Helper class.

Once tests are passing, I will be happy to QA.

**Comment by jessieay** [comment]
Hmmm that failure looks unrelated to this PR - re-running Circle. Will let you know once it's green!

**Comment by jessieay** [comment]
rebased and now it's green @pkarman

**Comment by pkarman** [comment]
[x] scenario (with reason)
[ ] scenario (no reason)

2nd failed with this error "A reason for cancellation is required. Please indicate why this request needs to be cancelled."

I was using a NCR work order. https://c2-dev.18f.gov/proposals/206/cancel_form

**Comment by jessieay** [comment]
Interesting, reason is required, I'd totally missed that! Can remove logic for situation without reason.

**Comment by jessieay** [comment]
@pkarman updated!

**Pull request merged**
