### PR TITLE
display cart properties on show page

### PR DESCRIPTION
**Pull request by afeld**
Thinking they should probably have less spacing, but was fighting with some conflicting styles a bit, so didn't want to spend much time on it before getting a second opition. @ericadeahl, thoughts on a quick fix for that middle section?

c2

### CODE REVIEW

**Comment by ericadeahl** [comment]
@afeld Middle section looks ok to me. I would just:
- reduce the spacing so each row is about half the height it is now
- left align the labels (left column of text) with the rules
- move the right column text over closer to the labels (so the labels column is 1/4 of the width, right column is 3/4 of the width) 

Is that what you need? I'm lacking some context info :)

**Comment by afeld** [comment]
@ericadeahl Exactly what I was looking for, thanks!

@phirefly Hold off on reviewing/merging this... going to split up into more focused PRs and do the layout changes suggested above.

**Comment by afeld** [comment]
Updated!

screen shot 2015-01-29 at 1 45 51 am

**Comment by phirefly** [comment]
@afeld: Does this PR include the desired splitting up of commits or should we still hold off on this?

**Comment by afeld** [comment]
Yep! Rebased and ready for review.

**Comment by phirefly** [comment]
Beauteous. :shipit:

**Pull request merged**
