### PR TITLE
Add more code climate checks

### PR DESCRIPTION
**Pull request by jessieay**
* List of engines: http://docs.codeclimate.com/article/296-engines-available-engines

### CODE REVIEW

**Comment by jessieay** [comment]
cc @afeld :) 

not sure what to do with the fact that code climate is failing now -- it is failing because the new checks are bringing up errors that the old checks didn't.

**Comment by afeld** [comment]
I say we merge, and worry about fixing existing warnings separately. 


:shipit:

**Comment by jessieay** [comment]
What do you think, @pkarman ?

**Comment by pkarman** [comment]
The definition of "similar code" might need some thinking about, but I am ok to merge this and see what happens.

**Comment by jessieay** [comment]
ok, works for me @pkarman !

**Pull request merged**
