### PR TITLE
Resolve Konacha test error

### PR DESCRIPTION
**Pull request by rememberlenny**
Konacha test runner complains about `tile/coffee`. 

This `require` resolves the issue.

### CODE REVIEW

**Comment by dogweather** [comment]
Can we delete the branch?

**Comment by rememberlenny** [comment]
@dogweather Always

**Comment by rememberlenny** [comment]
Always!

ᐧ

--
*Leonard Bogdonoff*
rememberlenny@gmail.com
Blog <http://blog.rememberlenny.com> | Portfolio <http://rememberlenny.com/>
 | @rememberlenny <http://twitter.com/rememberlenny>
949-322-8496

**Comment by dogweather** [comment]
Awesome

**Pull request merged**
