### PR TITLE
Add initial front end API reqs doc (WIP)

### PR DESCRIPTION
**Pull request by yozlet**

### CODE REVIEW

**Comment by jessieay** [comment]
Hey @yozlet  - thanks for putting this together

In the intro you write:

> we want users to browse and edit Proposals with fewer page reloads

I think that starting with 1 async request would be a good way to get started on the API. So rather than building out all of these endpoints upfront, we start with an interaction that needs an API endpoint and we build the endpoint for that use case.

What do you think of that plan?

**Comment by yozlet** [comment]
@jessieay Yes, that works for me. At a previous API discussion we had talked about me producing a rough tactics document about what the front end needs are and how we should implement, but I suspect this goes to deep into the specifics of individual endpoints.

**Comment by pkarman** [comment]
Could we start with a simple GET (JSON produced with `JSON.pretty_generate(proposal.as_indexed_json)`

```
GET /api/proposals/1234

{
  "id": 1234,
  "status": "pending",
  "created_at": "2016-02-25 21:44:03 UTC",
  "updated_at": "2016-02-25 21:44:34 UTC",
  "client_data_id": 7890,
  "client_data_type": "Ncr::WorkOrder",
  "requester_id": 184,
  "public_id": "FY16-1234",
  "visit_id": null,
  "comments": [

  ],
  "steps": [
    {
      "id": 12806,
      "user_id": null,
      "status": "actionable",
      "created_at": "2016-02-25 21:44:03 UTC",
      "updated_at": "2016-02-25 21:44:03 UTC",
      "position": 1,
      "proposal_id": 2737,
      "completed_at": null,
      "parent_id": null,
      "min_children_needed": null,
      "completer_id": null
    },
    {
      "id": 12807,
      "user_id": 275,
      "status": "completed",
      "created_at": "2016-02-25 21:44:03 UTC",
      "updated_at": "2016-02-25 21:44:34 UTC",
      "position": 2,
      "proposal_id": 2737,
      "completed_at": "2016-02-25 21:44:34 UTC",
      "parent_id": 12806,
      "min_children_needed": null,
      "completer_id": 275,
      "completed_by": {
        "display_name": "Some One <someone@example.com>"
      }
    },
    {
      "id": 12808,
      "user_id": 127,
      "status": "actionable",
      "created_at": "2016-02-25 21:44:03 UTC",
      "updated_at": "2016-02-25 21:44:34 UTC",
      "position": 3,
      "proposal_id": 2737,
      "completed_at": null,
      "parent_id": 12806,
      "min_children_needed": null,
      "completer_id": null,
      "completed_by": {
        "display_name": "approver@examle.com"
      }
    }
  ],
  "client_data": {
    "id": 7890,
    "amount": "2446.96",
    "expense_type": "BA80",
    "vendor": "Some Company",
    "not_to_exceed": false,
    "building_number": "DC0084ZZ - WILBER WRIGHT BLDG",
    "emergency": false,
    "rwa_number": "Fxxxxxxxx",
    "code": "",
    "project_title": "some title",
    "description": "some description",
    "created_at": "2016-02-25 21:44:03 UTC",
    "updated_at": "2016-02-25 21:44:03 UTC",
    "direct_pay": false,
    "cl_number": null,
    "function_code": null,
    "soc_code": null,
    "ncr_organization_id": 418,
    "approving_official_id": 275,
    "ncr_organization": {
      "id": 418,
      "created_at": "2015-12-28 20:27:20 UTC",
      "updated_at": "2015-12-28 20:27:20 UTC",
      "code": "P1127001",
      "name": "(192,442) DC SERVICES DIVISION"
    },
    "approving_official": {
      "id": 275,
      "email_address": "someone@example.com",
      "first_name": "Some",
      "last_name": "One",
      "created_at": "2015-06-10 02:30:58 UTC",
      "updated_at": "2015-06-10 02:30:58 UTC",
      "client_slug": "ncr",
      "active": true
    }
  },
  "requester": "A Requester <arequester@example.com",
  "subscribers": [
    {
      "id": 275,
      "name": "Some One <someone@example.com"
    }
  ],
  "num_attachments": 1
}

```

**Comment by pkarman** [comment]
for a "write" URL endpoint strategy, how about segmenting the related objects to reflect the db structure:

```
PUT /api/v0/proposals/1234
{
  "id": 1234,
  "status": "pending",
  "created_at": "2016-02-25 21:44:03 UTC",
  "updated_at": "2016-02-25 21:44:34 UTC",
  "client_data_id": 7890,
  "client_data_type": "Ncr::WorkOrder",
  "requester_id": 184,
  "public_id": "FY16-1234"
}
```

```
POST /api/v0/proposals/1234/client_data
{
    "amount": "2446.96",
    "expense_type": "BA80",
    "vendor": "Some Company",
    "not_to_exceed": false,
    "building_number": "DC0084ZZ - WILBER WRIGHT BLDG",
    "emergency": false,
    "rwa_number": "Fxxxxxxxx",
    "work_order_code": "abc123",
    "project_title": "some title",
    "description": "some description",
    "created_at": "2016-02-25 21:44:03 UTC",
    "updated_at": "2016-02-25 21:44:03 UTC",
    "direct_pay": false,
    "cl_number": null,
    "function_code": null,
    "soc_code": null,
    "ncr_organization_id": 418,
    "approving_official_id": 275,
}
```

**Comment by pkarman** [comment]
cc/ @adelevie @rememberlenny @yozlet you will likely want to read through this PR before our meeting today.

**Comment by pkarman** [comment]
@yozlet I am going to close this -- I have opened #1160 based on this and our conversation.

**Pull request closed without merging**
