### PR TITLE
[Delivers #106870524] add data retention policy per GSA audit guide

### PR DESCRIPTION
**Pull request by pkarman**
Story: https://www.pivotaltracker.com/story/show/106870524

Documentation only.

See also https://github.com/18F/DevOps/issues/512

### CODE REVIEW

**Comment by yozlet** [comment]
Should this be linked somewhere from the app?

**Comment by pkarman** [comment]
@yozlet that's a good question.

This story was not initiated on behalf of the users; I initiated it a few weeks ago because I didn't know what the rules where. In some ways, the users shouldn't have to worry about the issue at all -- their data will be available in conformance with the Rules as Long As It Needs To Be. Now we just have a definition for "Long".

I'm happy to add a link, I just don't know where. The target audience for this doc is really us (developers and system administrators).

**Comment by jessieay** [comment]
maybe we should have a docs index page (a markdown file, most likely) that links to all of our docs / gives a brief explanation of each. I know that for myself that I never know if the info i need will be in `setup` or `developer-onboarding`, so that type of page would be very helpful for me!

**Comment by pkarman** [comment]
@jessieay that sounds great, but outside the scope of this story, which is just to identify and document what the policy is. Organizing the docs for the sake of developers is fine, if that's an itch you want to scratch. For me, I just use `grep`.

**Comment by jessieay** [comment]
ok we can do it separately. should Raphy read this before we merge? looks good to me

**Comment by pkarman** [comment]
@phirefly please review before we merge

**Comment by jessieay** [comment]
ping ping @phirefly

**Comment by phirefly** [comment]
:shipit:

**Pull request merged**
