### PR TITLE
[#86660976] Removed rejection reply tip

### PR DESCRIPTION
**Pull request by phirefly**

### CODE REVIEW

**Comment by afeld** [comment]
Do we still want to leave this bit in at the top?

```
------------------ 
Please reply to this email with the response 'APPROVE' or 'REJECT' on its own line. 
Additional comments:
```

If yes, :shipit:

**Comment by aminedak15** [comment]
lf yes amine yo ablo arbic

**Comment by aminedak15** [comment]
Do we still want to leave this bit in at the top?

**Comment by phirefly** [comment]
Yep, we'll keep this for now. Thanks!

**Pull request merged**
