### PR TITLE
add comments via ajax

### PR DESCRIPTION
**Pull request by nickbristow**
Its not the best, but its pretty straightforward. 

Get the text value and current user, and adds a new comment. All the HTML is just copied from the page. 

It does actually submit the comment so its there when you refresh. 

@rememberlenny @yozlet

### CODE REVIEW

**Comment by nickbristow** [comment]
The ajax does return a failed response...but it does post

**Comment by rememberlenny** [comment]
@nickbristow Looks good! Can you put the JS in the `redesign/detail.js` file?

**Comment by nickbristow** [comment]
@rememberlenny sure, uh oh failed a test.

**Comment by rememberlenny** [comment]
@nickbristow At this point, dont worry too much about the tests

**Comment by nickbristow** [comment]
@rememberlenny ok, should be good to merge then. Added a hidden div with the current user so the JS could grab it.

**Comment by rememberlenny** [comment]
@nickbristow Getting merge conflicts

**Comment by nickbristow** [comment]
coool

**Pull request merged**
