### PR TITLE
added style for wordwrapping filenames of attachments

### PR DESCRIPTION
**Pull request by nickbristow**
Don't merge yet

### CODE REVIEW

**Comment by nickbristow** [comment]
ncr_name_-_c2

**Comment by nickbristow** [comment]
https://trello.com/c/gDqJHl32/404-attachment-display-in-current-app

**Comment by rememberlenny** [comment]
@nickbristow Not ready to merge yet?

**Comment by nickbristow** [comment]
@rememberlenny not yet, need to fix another thing and clarify with @amberwreed

**Comment by rememberlenny** [comment]
Changing the name for now

**Comment by nickbristow** [comment]
@rememberlenny ready for review

**Comment by rememberlenny** [comment]
@nickbristow Looks good!

**Pull request merged**
