### PR TITLE
Notification for reapproval when saving in design page

### PR DESCRIPTION
**Pull request by nickbristow**
Notifies the user if there is a reapproval needed based on the changes 

c2

## Why

So the user can see what actions they are doing are causing a reapproval to occur

## What

Notifies the user when modifying the proposal will trigger a re-approval from budget. 

## To Do

Test needs to be written, 
Refactoring (code is brittle atm)

https://trello.com/c/1FQrlVWY/322-as-a-user-who-is-modifying-a-request-i-will-be-warned-that-this-action-will-trigger-a-re-approval-process

### CODE REVIEW

**Comment by rememberlenny** [comment]
@nickbristow I dont know what Im doing wrong, but I can't get the `data-reapproval` to ever equal true. Is there something Im missing?

**Comment by nickbristow** [comment]
It needs to be a ba80, it needs to be complete and you can't be logged in
as an approver.

On Friday, July 8, 2016, Leonard Bogdonoff <notifications@github.com> wrote:

> @nickbristow <https://github.com/nickbristow> I dont know what Im doing
> wrong, but I can't get the data-reapproval to ever equal true. Is there
> something Im missing?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/C2/pull/1394#issuecomment-231488363>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AFDQeOXZ5WZs1EMU94fiOIZNFFM71kePks5qTs_pgaJpZM4JIIPp>
> .
>


-- 
Nick Bristow
18F Innovation Specialist
Nick.Bristow@gsa.gov

**Comment by rememberlenny** [comment]
@nickbristow Im going to leave this for when you get back. Seems like there is more to this than is written in description.

**Comment by rememberlenny** [comment]
Looks good!

**Pull request merged**
