### PR TITLE
simplify assignment of WorkOrder#approving_official_email

### PR DESCRIPTION
**Pull request by afeld**
Moved from #736, to have a target of `master`.

### CODE REVIEW

**Comment by pkarman** [comment]
@afeld seems like `wo.reload` is "fixing" the failing tests, but that seems to indicate that there is some check for `.approvers` in the creation process that is caching the empty array. Fixing that initial caching is probably what is best. I think that's what the original `approvers.any?` line had the side effect of doing.

**Comment by afeld** [comment]
Btw, I rebased this branch when creating the new pull request and that seems to have made duplicate commits...let's squash before merging. I'll try and look into this deeper at some point today, unless you want to keep playing with it. Thanks for the help!

**Comment by pkarman** [comment]
If it were up to me, I would just clarify the comment since we now know why the `.approvers.any?` check is there, and/or add an explicit `.approvers(true)` inside `set_defaults`.

**Comment by afeld** [comment]
Not sure that this is worth spending that much time on. Closing for now.

**Pull request closed without merging**
