### PR TITLE
Admin manage reports

### PR DESCRIPTION
**Pull request by pkarman**
Trello: https://trello.com/c/QdccUTC4

### CODE REVIEW

**Comment by jessieay** [comment]
this looks great! QA instructions?

**Comment by pkarman** [comment]
QA steps:

* go to `/admin`
* confirm there is a `Reports` menu option
* create new Report. The `text` query value should be a search string, the `humanized` string can be whatever you want (see attached screenshot).
* edit a Report.
* confirm changes appear at `/reports/`

screen shot 2016-03-02 at 2 02 27 pm

**Comment by jessieay** [comment]
argh trying to QA. need to make myself an admin on my dev instance. getting this error (unrelated to this PR but thought I'd ask here)

```
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activeadmin'. (Bundler::GemRequireError)
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /home/vcap/app/config/application.rb:5:in `<top (required)>'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:141:in `require'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:67:in `console'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/vcap/app/bin/rails:8:in `require'
        from /home/vcap/app/bin/rails:8:in `<main>'
```

**Comment by pkarman** [comment]
@jessieay weird error haven't seen that.

maybe try `bundle exec rails c` instead?

**Comment by jessieay** [comment]
ok got this running on my dev env. getting error when I try to create a report at https://c2-dev-jessieay.18f.gov/admin/reports/new

also getting an error when I try to create a report via search, though, so perhaps an issue with my dev env search setup?

https://c2-dev-jessieay.18f.gov/proposals/query?ncr_work_order%5Bstatus%5D=*&ncr_work_order%5Brequester%5D=&ncr_work_order%5Bclient_data.vendor%5D=&ncr_work_order%5Bclient_data.amount%5D=&ncr_work_order%5Bclient_data.expense_type%5D=*&ncr_work_order%5Bcreated_within%5D=1+year&ncr_work_order%5Bcreated_at%5D=&text=Test

(url renders error)

**Comment by pkarman** [comment]
works in this env:

https://c2-dev-pkarman.18f.gov/proposals/query?ncr_work_order%5Bstatus%5D=*&ncr_work_order%5Brequester%5D=&ncr_work_order%5Bclient_data.vendor%5D=&ncr_work_order%5Bclient_data.amount%5D=&ncr_work_order%5Bclient_data.expense_type%5D=*&ncr_work_order%5Bcreated_within%5D=1+year&ncr_work_order%5Bcreated_at%5D=&text=Test

**Comment by jessieay** [comment]
ah yes had to index es on my dev env.

saving as report and viewing in admin works. creating a report in admin still does't . backtrace:

```
ActionController::RoutingError (No route matches [PUT] "/admin/reports"):
```

if we want this behavior we should add route. otherwise we should remove the "create report" button from admin

**Comment by pkarman** [comment]
the problem is POST for create and PUT for edit. I will try and figure out how to work around that.

**Comment by pkarman** [comment]
@jessieay 77539d7 works for me locally

**Comment by pkarman** [comment]
@jessieay all :green_heart: again

**Comment by jessieay** [comment]
looks good on dev! that json field in active admin sure is ugly, but it'll do :pig:

**Pull request merged**
